import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of use — Onside",
  description:
    "The terms governing your use of Onside. Valuations are informational model estimates, not financial, investment, or transfer advice. No warranty. Acceptable use and intellectual property.",
};

const LAST_UPDATED = "2 June 2026";
const CONTACT = "legal@onsidemarket.com";

/** Shared section heading for the legal pages. */
function LegalSection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mt-10 scroll-mt-24">
      <h2 className="text-xl md:text-2xl display tracking-tight">{title}</h2>
      <div className="mt-3 space-y-3 text-[15px] text-mute leading-relaxed">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="max-w-[1440px] mx-auto px-6 py-16 sm:py-20">
      <div className="max-w-[720px] mx-auto">
        {/* Hero */}
        <div className="text-[11px] uppercase tracking-[0.18em] text-mute-soft mb-3 num">Legal</div>
        <h1 className="display text-[clamp(30px,5vw,46px)] leading-[1.04] tracking-[-0.04em]">
          Terms of <span className="font-serif italic font-normal text-acc">use</span>
        </h1>
        <p className="text-[13px] text-mute-soft mt-4 num">Last updated: {LAST_UPDATED}</p>
        <p className="text-[16px] text-mute mt-5 leading-relaxed">
          These terms govern your use of Onside. By accessing or using the site or app, you agree to them. If
          you don't agree, please don't use Onside. We've kept them readable, but they are the binding
          agreement between you and us.
        </p>

        <LegalSection id="who-we-are" title="Who these terms are with">
          <p>
            Onside (&ldquo;Onside&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) provides a football data and
            valuation product. &ldquo;You&rdquo; means anyone who accesses or uses it. Questions about these
            terms can go to{" "}
            <a href={`mailto:${CONTACT}`} className="text-fg font-medium hover:text-acc transition">
              {CONTACT}
            </a>
            .
          </p>
        </LegalSection>

        {/* The headline disclaimer — load-bearing */}
        <LegalSection id="not-advice" title="Valuations are informational — not advice">
          <p>
            This is the most important thing on this page, so read it carefully. Every valuation, score,
            confidence band, daily &ldquo;Pulse&rdquo; movement, and projection on Onside is an{" "}
            <strong className="text-fg">informational model estimate</strong>, generated by our own
            algorithm from the data described in our{" "}
            <Link href="/methodology" className="text-fg font-medium hover:text-acc transition">
              methodology
            </Link>
            .
          </p>
          <p>
            Onside is <strong className="text-fg">not</strong> financial advice, investment advice, a
            securities recommendation, a betting tip, a transfer fee, a market price, an offer, a valuation
            for accounting, tax, or contractual purposes, or professional advice of any kind. Our figures do
            not represent the price at which any player has been, is, or will be transferred. You should not
            rely on Onside to make financial, betting, commercial, or transfer decisions, and any decision you
            make is your own responsibility. If you need advice, consult a suitably qualified professional.
          </p>
        </LegalSection>

        <LegalSection id="no-warranty" title="No warranty">
          <p>
            Onside is provided <strong className="text-fg">&ldquo;as is&rdquo; and &ldquo;as
            available&rdquo;</strong>, without warranties of any kind, whether express or implied, including
            any implied warranties of accuracy, completeness, merchantability, fitness for a particular
            purpose, or non-infringement. We draw on third-party data that may contain errors, gaps, or
            delays, and our model is an estimate by design. We don't warrant that the service will be
            uninterrupted, error-free, or that any valuation is correct.
          </p>
        </LegalSection>

        <LegalSection id="liability" title="Limitation of liability">
          <p>
            To the fullest extent permitted by law, Onside and its affiliates will not be liable for any
            indirect, incidental, special, consequential, or punitive damages, or for any loss of profits,
            revenue, data, or goodwill, arising from your use of — or inability to use — the service or any
            reliance on its valuations. Nothing in these terms excludes liability that cannot lawfully be
            excluded.
          </p>
        </LegalSection>

        <LegalSection id="acceptable-use" title="Acceptable use">
          <p>You agree not to:</p>
          <ul className="space-y-3 pl-1">
            <li className="flex gap-3">
              <span className="text-acc mt-1.5 text-[10px]">&#9679;</span>
              <span>
                Scrape, harvest, or systematically extract data from Onside, or use bots or automated means
                to access it, except as expressly permitted.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="text-acc mt-1.5 text-[10px]">&#9679;</span>
              <span>
                Resell, redistribute, or commercially exploit our valuations or data without our written
                permission.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="text-acc mt-1.5 text-[10px]">&#9679;</span>
              <span>Interfere with, disrupt, or attempt to gain unauthorised access to the service or its systems.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-acc mt-1.5 text-[10px]">&#9679;</span>
              <span>Misrepresent our figures as official prices, fees, or anything other than model estimates.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-acc mt-1.5 text-[10px]">&#9679;</span>
              <span>Use Onside for any unlawful purpose or in breach of these terms.</span>
            </li>
          </ul>
        </LegalSection>

        <LegalSection id="accounts" title="Your account">
          <p>
            If you create an account, you're responsible for keeping your credentials secure and for activity
            under your account. Let us know promptly of any unauthorised use. We may suspend or terminate
            accounts that breach these terms. Your use of any account data is also governed by our{" "}
            <Link href="/privacy" className="text-fg font-medium hover:text-acc transition">
              privacy policy
            </Link>
            .
          </p>
        </LegalSection>

        <LegalSection id="ip" title="Intellectual property">
          <p>
            Onside — including the valuation model, software, design, branding, text, and the compiled
            valuations and presentation of data — is owned by Onside or its licensors and protected by
            intellectual property laws. We grant you a limited, personal, non-exclusive, non-transferable,
            revocable licence to access and use Onside for your own personal, non-commercial use. All rights
            not expressly granted are reserved. Underlying third-party data remains the property of its
            respective owners; see our{" "}
            <Link href="/data-sources" className="text-fg font-medium hover:text-acc transition">
              data &amp; sources
            </Link>{" "}
            page.
          </p>
        </LegalSection>

        <LegalSection id="affiliation" title="No affiliation">
          <p>
            Onside is not affiliated with, endorsed by, or associated with FIFA or any league, club, or
            governing body. References to competitions, including the &ldquo;World Cup&rdquo;, are descriptive
            only. We do not use licensed player photographs or club crests.
          </p>
        </LegalSection>

        <LegalSection id="third-party" title="Third-party links">
          <p>
            Onside may link to third-party sites and sources. We don't control them and aren't responsible for
            their content, accuracy, or practices. Following a link is at your own risk.
          </p>
        </LegalSection>

        <LegalSection id="changes" title="Changes to the service &amp; these terms">
          <p>
            We're actively building Onside, so features may change, and we may update these terms from time to
            time. When we make material changes, we'll update the date above. Continuing to use Onside after a
            change means you accept the updated terms.
          </p>
        </LegalSection>

        <LegalSection id="governing-law" title="Governing law">
          <p>
            These terms are governed by the laws of <strong className="text-fg">[governing jurisdiction
            to be confirmed]</strong>, and the courts of that jurisdiction will have exclusive jurisdiction
            over any dispute, without prejudice to any mandatory consumer-protection rights you have where you
            live.
          </p>
        </LegalSection>

        <LegalSection id="contact" title="Contact">
          <p>
            Questions about these terms? Email{" "}
            <a href={`mailto:${CONTACT}`} className="text-fg font-medium hover:text-acc transition">
              {CONTACT}
            </a>
            .
          </p>
        </LegalSection>

        {/* Cross-link */}
        <div className="mt-12 pt-8 border-t border-line">
          <p className="text-[13px] text-mute-soft">
            See also our{" "}
            <Link href="/privacy" className="text-mute hover:text-fg transition">
              Privacy policy
            </Link>{" "}
            and{" "}
            <Link href="/data-sources" className="text-mute hover:text-fg transition">
              Data &amp; sources
            </Link>
            .
          </p>
        </div>
      </div>
    </div>
  );
}
